/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Decimal = ColumnType<string, number | string>;

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Commune {
  id: number;
  province_id: number;
}

export interface DbAdmin {
  expires_at: Date | null;
  id: Generated<number>;
  password: string;
  role: Generated<"admin" | "super">;
  session_token: string | null;
  username: string;
}

export interface Food {
  brand: string | null;
  code: string;
  group_id: number;
  id: Generated<number>;
  observation: string | null;
  scientific_name_id: number | null;
  strain: string | null;
  subspecies_id: number | null;
  type_id: number;
}

export interface FoodGroup {
  code: string;
  id: Generated<number>;
  name: string;
}

export interface FoodLangualCode {
  food_id: number;
  langual_id: number;
}

export interface FoodOrigin {
  food_id: number;
  origin_id: number;
}

export interface FoodTranslation {
  common_name: string | null;
  food_id: number;
  ingredients: string | null;
  language_id: number;
}

export interface FoodType {
  code: string;
  id: Generated<number>;
  name: string;
}

export interface Journal {
  id: Generated<number>;
  name: string;
}

export interface JournalVolume {
  id: Generated<number>;
  issue: number;
  journal_id: number;
  volume: number;
  year: number;
}

export interface Language {
  code: "en" | "es" | "pt";
  id: Generated<number>;
  name: string;
}

export interface LangualCode {
  code: string;
  descriptor: string;
  id: Generated<number>;
  parent_id: number | null;
}

export interface Location {
  commune_id: number;
  id: number;
  type: "city" | "town";
}

export interface Measurement {
  average: Decimal;
  data_type: "analytic" | "assumed" | "borrowed" | "calculated";
  deviation: Decimal | null;
  food_id: number;
  id: Generated<number>;
  max: Decimal | null;
  min: Decimal | null;
  nutrient_id: number;
  sample_size: number | null;
}

export interface MeasurementReference {
  measurement_id: number;
  reference_code: number;
}

export interface Micronutrient {
  id: number;
  type: "mineral" | "vitamin";
}

export interface Migrations {
  id: Generated<number>;
  name: string;
  run_on: Date;
}

export interface Nutrient {
  id: Generated<number>;
  measurement_unit: string;
  name: string;
  note: string | null;
  standardized: Generated<number>;
  type: "component" | "energy" | "macronutrient" | "micronutrient";
}

export interface NutrientComponent {
  id: number;
  macronutrient_id: number;
}

export interface Origin {
  id: Generated<number>;
  name: string;
  type: "commune" | "location" | "province" | "region";
}

export interface Province {
  id: number;
  region_id: number;
}

export interface RefArticle {
  id: Generated<number>;
  page_end: number;
  page_start: number;
  volume_id: number;
}

export interface RefAuthor {
  id: Generated<number>;
  name: string;
}

export interface RefCity {
  id: Generated<number>;
  name: string;
}

export interface Reference {
  code: number;
  other: string | null;
  ref_article_id: number | null;
  ref_city_id: number | null;
  text: string;
  title: string;
  type: "article" | "book" | "report" | "thesis" | "website";
  year: number | null;
}

export interface ReferenceAuthor {
  author_id: number;
  reference_code: number;
}

export interface Region {
  id: number;
  number: number;
  place: number;
}

export interface ScientificName {
  id: Generated<number>;
  name: string;
}

export interface Subspecies {
  id: Generated<number>;
  name: string;
}

export interface DB {
  commune: Commune;
  db_admin: DbAdmin;
  food: Food;
  food_group: FoodGroup;
  food_langual_code: FoodLangualCode;
  food_origin: FoodOrigin;
  food_translation: FoodTranslation;
  food_type: FoodType;
  journal: Journal;
  journal_volume: JournalVolume;
  language: Language;
  langual_code: LangualCode;
  location: Location;
  measurement: Measurement;
  measurement_reference: MeasurementReference;
  micronutrient: Micronutrient;
  migrations: Migrations;
  nutrient: Nutrient;
  nutrient_component: NutrientComponent;
  origin: Origin;
  province: Province;
  ref_article: RefArticle;
  ref_author: RefAuthor;
  ref_city: RefCity;
  reference: Reference;
  reference_author: ReferenceAuthor;
  region: Region;
  scientific_name: ScientificName;
  subspecies: Subspecies;
}
